### ISSUE TITLE
BaseML在模型训练时遇到的奇怪问题

### ISSUE THREAD

**Issue by littlestone0806** [OpenXLab-Edu/OpenBaseLab-Edu#15]
作者您好，我在用BaseML执行模型训练时，意外出现了以下报错。但是在我重新安装了BaseDT和BaseML之后，报错又消失了。不过所有算法的评估验证准确率都是100%，感觉有些奇怪，恳请解答。（BaseDT==0.1.3  BaseML==0.1.5）
Traceback (most recent call last):
  File "C:\Users\stone\Desktop\mediapipe\train.py", line 9, in <module>
    model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')  # 模型评估
  File "C:\Users\stone\Desktop\mediapipe\python38\Lib\site-packages\BaseML\base.py", line 290, in valid
    score = accuracy_score(y, y_pred)
  File "C:\Users\stone\Desktop\mediapipe\python38\Lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\stone\Desktop\mediapipe\python38\Lib\site-packages\sklearn\metrics\_classification.py", line 220, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "C:\Users\stone\Desktop\mediapipe\python38\Lib\site-packages\sklearn\metrics\_classification.py", line 84, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "C:\Users\stone\Desktop\mediapipe\python38\Lib\site-packages\sklearn\utils\validation.py", line 407, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [56, 2]

![image](https://github.com/user-attachments/assets/b0def0af-63b8-4ae9-9c3e-0f289cfac8b4)

以下是train.py
# 导入BaseML的分类模块
from BaseML import Classification as cls

# 可自行调整评分最高的算法
model = cls('KNN')  # K近临分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()  # 模型训练
print("KNN", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')  # 模型评估
model.save('checkpoints/mediapipe_pose_KNN_mode.pkl')

model = cls('SVM')  # 支持向量机分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("SVM", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_SVM_mode.pkl')

model = cls('NaiveBayes')  # 朴素贝叶斯分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("NaiveBayes", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_NaiveBayes_mode.pkl')

model = cls('CART')  # 决策树分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("CART", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_CART_mode.pkl')

model = cls('AdaBoost')  # 自适应增强分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("AdaBoost", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_AdaBoost_mode.pkl')

model = cls('MLP')  # 多层感知机分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("MLP", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_MLP_mode.pkl')

model = cls('RandomForest')  # 随机森林分类
model.load_tab_data('feature_data/mediapipe_pose_train.csv')  # 载入训练数据
model.train()
print("RandomForest", end='')
model.valid('feature_data/mediapipe_pose_val.csv', metrics='acc')
model.save('checkpoints/mediapipe_pose_RandomForest_mode.pkl')

**Comment by littlestone0806** [comment]
已解决，我为了能输出预测分值，修改了BaseML中的BaseClassification.py中第139行，造成了报错问题
        if self.algorithm in ['AdaBoost', 'SVM', 'NaiveBayes', 'MLP', 'KNN', 'CART', 'RandomForest']:
            pred = self.model.predict(x_test)
            scores = self.model.predict_proba(x_test)
            return pred, scores
